#:schema node_modules/wrangler/config-schema.json
name = "dovedit-fetcher"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["0 */12 * * *"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "dovedit-db"
database_id = "4a4703aa-c0ee-4898-abae-4121414467a1"
